name: Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'model.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag model:latest

    - name: Test the Docker image
      run: docker run model:latest
