name: MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'model.py'
      - 'metrics.py'

jobs:
  # Job 1: Test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  # Job 2: Evaluation
  evaluate:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Evaluate model
        run: python metrics.py

      - name: Upload metrics
        uses: actions/upload-artifact@v3
        with:
          name: model-metrics
          path: metrics.json

  # Job 3: Build Docker Image
  package:
    needs: evaluate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag model:latest

      - name: Test Docker image
        run: |
          docker run model:latest

  # Job 4: Deploy to Development
  deploy-dev:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        run: |
          echo "Deploying to development environment..."

  # Job 5: Deploy to Production (manual approval)
  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Waiting for manual approval
        run: |
          echo "Waiting for manual approval..."
      
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
