name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Spécifie une version précise de Python (par exemple, 3.10)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances depuis requirements.txt

      - name: Verify pytest installation
        run: |
          pip show pytest  # Vérifie que pytest est bien installé

      - name: Run tests
        run: |
          pytest  # Lance pytest pour exécuter les tests
